---
- name: AWS credential rotation with Vault
  hosts: localhost
  gather_facts: false
  vars:
    vault_addr: "http://127.0.0.1:8200"
    vault_token: "{{ lookup('env', 'VAULT_TOKEN') }}"
    aws_role: "ec2-admin"  # The AWS role configured in Vault

  tasks:
    - name: Ensure hvac and boto3 are installed
      pip:
        name:
          - hvac
          - boto3
        state: present
      become: false

    - name: Get temporary AWS credentials from Vault
      uri:
        url: "{{ vault_addr }}/v1/aws/creds/{{ aws_role }}"
        method: GET
        headers:
          X-Vault-Token: "{{ vault_token }}"
        status_code: 200
        body_format: json
      register: aws_creds
      no_log: true

    - name: Set AWS environment variables
      set_fact:
        aws_access_key: "{{ aws_creds.json.data.access_key }}"
        aws_secret_key: "{{ aws_creds.json.data.secret_key }}"
        aws_lease_id: "{{ aws_creds.json.lease_id }}"
      no_log: true

    - name: Display lease information
      debug:
        msg: "Lease ID: {{ aws_lease_id }}, Lease Duration: {{ aws_creds.json.lease_duration }} seconds"

    - name: Create AWS credentials file
      copy:
        dest: "~/.aws/credentials.temp"
        content: |
          [temp]
          aws_access_key_id = {{ aws_access_key }}
          aws_secret_access_key = {{ aws_secret_key }}
        mode: 0600
      no_log: true

    - name: Test AWS credentials with a simple command
      shell: aws s3 ls --profile temp
      environment:
        AWS_CONFIG_FILE: "~/.aws/config"
        AWS_SHARED_CREDENTIALS_FILE: "~/.aws/credentials.temp"
      register: aws_test
      failed_when: false
      changed_when: false

    - name: Display AWS command result
      debug:
        var: aws_test.stdout_lines

    - name: Clean up temporary credentials file
      file:
        path: "~/.aws/credentials.temp"
        state: absent

    - name: Revoke Vault lease when done
      uri:
        url: "{{ vault_addr }}/v1/sys/leases/revoke"
        method: PUT
        headers:
          X-Vault-Token: "{{ vault_token }}"
        body_format: json
        body:
          lease_id: "{{ aws_lease_id }}"
        status_code: 204
      when: aws_lease_id is defined
